const LOCATIONS = [
    { text: "Droughts", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/10/Borderlands-3-Black-Market-Location-Map-Week-28.jpg" },
    { text: "Droughts", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/10/Borderlands-3-Black-Market-Location-Map-Week-28.jpg" },
    { text: "Droughts", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/06/Borderlands-3-Black-Market-Location-Map-Week-10.jpg" },
    { text: "Ascension Bluff", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/09/Borderlands-3-Black-Market-Location-Map-Ascension-Bluff.jpg" },
    { text: "Ascension Bluff", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/04/Borderlands-3-Black-Market-Location-Map-Week-2.jpg" },
    { text: "Ascension Bluff", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/09/Borderlands-3-Black-Market-Location-Map-Week-25.jpg" },
    { text: "Atlas HQ", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2023/01/Borderlands-3-Black-Market-Location-Map-Atlas-HQ.jpg" },
    { text: "Atlas HQ", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/06/Borderlands-3-Black-Market-Location-Map-Week-11.jpg" },
    { text: "Atlas HQ", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/12/Borderlands-3-Black-Market-Location-Map-Week-36.jpg" },
    { text: "Meridian Metroplex", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/08/Borderlands-3-Black-Market-Location-Map-Week-20.jpg" },
    { text: "Meridian Metroplex", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/01/Borderlands-3-Black-Market-Location-Map-Week-41.jpg" },
    { text: "Nowhere! This location is forcibly disabled.", disabled: true, url: "https://cdn.discordapp.com/attachments/790257291923947551/1099948253287546950/image.png" },
    { text: "Neon Arterial", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/04/Borderlands-3-Black-Market-Location-Map-Week-56.jpg" },
    { text: "Neon Arterial", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/09/Borderlands-3-Black-Market-Location-Map-Week-23.jpg" },
    { text: "Athenas", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/07/Borderlands-3-Black-Market-Location-Map-Athenas.jpg" },
    { text: "Athenas", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/08/Borderlands-3-Black-Market-Location-Map-Athenas2.jpg" },
    { text: "Athenas", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/08/Borderlands-3-Black-Market-Location-Map-Week-18.jpg" },
    { text: "Skywell-27", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/05/Borderlands-3-Black-Market-Location-Map-Week-7.jpg" },
    { text: "Skywell-27", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/11/Borderlands-3-Black-Market-Location-Map-Skywell-27.jpg" },
    { text: "Skywell-27", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/11/Borderlands-3-Black-Market-Location-Map-Week-32.jpg" },
    { text: "Meridian Outskirts", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2023/01/Borderlands-3-Black-Market-Location-Map-Meridian-Outskirts.jpg" },
    { text: "Meridian Outskirts", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/03/Borderlands-3-Black-Market-Location-Map-Week-49.jpg" },
    { text: "Meridian Outskirts", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/07/Borderlands-3-Black-Market-Location-Map-Week-15.jpg" },
    { text: "Lectra City", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/04/Borderlands-3-Black-Market-Location-Map-Week-3.jpg" },
    { text: "Lectra City", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/01/Borderlands-3-Black-Market-Location-Map-Week-44.jpg" },
    { text: "Lectra City", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/09/Borderlands-3-Black-Market-Location-Map-Week-24.jpg" },
    { text: "Jakobs Estate", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/10/Borderlands-3-Black-Market-Location-Map-Week-29.jpg" },
    { text: "Jakobs Estate", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/08/Borderlands-3-Black-Market-Location-Map-Week-19.jpg" },
    { text: "Jakobs Estate", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2023/01/Borderlands-3-Black-Market-Location-Map-Jakobs-Estate.jpg" },
    { text: "Ambermire", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/04/Borderlands-3-Black-Market-Location-Week-01.jpg" },
    { text: "Ambermire", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/08/Borderlands-3-Black-Market-Location-Map-Ambermire.jpg" },
    { text: "Ambermire", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/09/Borderlands-3-Black-Market-Location-Map-Week-27.jpg" },
    { text: "Anvil", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/05/Borderlands-3-Black-Market-Location-Map-Week-6.jpg" },
    { text: "Anvil", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/12/Borderlands-3-Black-Market-Location-Map-The-Anvil.jpg" },
    { text: "Anvil", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/10/Borderlands-3-Black-Market-Location-Map-Week-31.jpg" },
    { text: "Voracious Canopy", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/03/Borderlands-3-Black-Market-Location-Map-Week-52.jpg" },
    { text: "Voracious Canopy", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/12/Borderlands-3-Black-Market-Location-Map-Week-37.jpg" },
    { text: "Voracious Canopy", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/06/Borderlands-3-Black-Market-Location-Map-Week-13.jpg" },
    { text: "Floodmoor Basin", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/08/Borderlands-3-Black-Market-Location-Map-Week-22.jpg" },
    { text: "Floodmoor Basin", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/04/Borderlands-3-Black-Market-Location-Map-Week-57.jpg" },
    { text: "Floodmoor Basin", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2023/02/Borderlands-3-Black-Market-Location-Map-Floodmoor-Basin.jpg" },
    { text: "Blackbarrel Cellars", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/06/Borderlands-3-Black-Market-Location-Map-Week-12.jpg" },
    { text: "Blackbarrel Cellars", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/08/Borderlands-3-Black-Market-Location-Map-Blackbarrel-Cellars.jpg" },
    { text: "Blackbarrel Cellars", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/09/Borderlands-3-Black-Market-Location-Map-Blackbarrel-Cellars2.jpg" },
    { text: "Devil's Razor", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/10/Borderlands-3-Black-Market-Location-Map-Devils-Razor.jpg?ssl=1" },
    { text: "Devil's Razor", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/07/Borderlands-3-Black-Market-Location-Map-Week-16.jpg" },
    { text: "Devil's Razor", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/12/Borderlands-3-Black-Market-Location-Map-Devils-Razor2.jpg" },
    { text: "Cathedral of the Twin Gods", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/07/Borderlands-3-Black-Market-Location-Map-Week-17.jpg" },
    { text: "Cathedral of the Twin Gods", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/11/Borderlands-3-Black-Market-Location-Map-Week-35.jpg" },
    { text: "Cathedral of the Twin Gods", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/02/Borderlands-3-Black-Market-Location-Map-Week-45.jpg" },
    { text: "Konrad's Hold", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/05/Borderlands-3-Black-Market-Location-Map-Week-8.jpg" },
    { text: "Konrad's Hold", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/03/Borderlands-3-Black-Market-Location-Map-Week-49.jpg" },
    { text: "Konrad's Hold", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/04/Borderlands-3-Black-Market-Location-Map-Week-55.jpg" },
    { text: "Splinterlands", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2023/02/Borderlands-3-Black-Market-Location-Map-Splinterlands-2.jpg" },
    { text: "Splinterlands", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/06/Borderlands-3-Black-Market-Location-Map-Splinterlands.jpg" },
    { text: "Splinterlands", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/08/Borderlands-3-Black-Market-Location-Map-Week-21.jpg" },
    { text: "Carnivora", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/04/Borderlands-3-Black-Market-Location-Map-Week-5.jpg" },
    { text: "Carnivora", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/10/Borderlands-3-Black-Market-Location-Map-Carnivora.jpg" },
    { text: "Tazandeer Ruins", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/11/Borderlands-3-Black-Market-Location-Map-Tazendeer-Ruins.jpg" },
    { text: "Tazandeer Ruins", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/12/Borderlands-3-Black-Market-Location-Map-Tazendeer-Ruins-2.jpg" },
    { text: "Tazandeer Ruins", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/04/Borderlands-3-Black-Market-Location-Map-Week-4.jpg" },
    { text: "Pyre of Stars", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/09/Borderlands-3-Black-Market-Location-Map-Week-26.jpg" },
    { text: "Pyre of Stars", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/05/Borderlands-3-Black-Market-Location-Map-Week-9.jpg" },
    { text: "Desolation's Edge", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/07/Borderlands-3-Black-Market-Location-Map-Week-14.jpg" },
    { text: "Desolation's Edge", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2021/07/Borderlands-3-Black-Market-Location-Map-Week-14.jpg" },
    { text: "Desolation's Edge", url: "https://i0.wp.com/mentalmars.com/wp-content/uploads/2022/03/Borderlands-3-Black-Market-Location-Map-Week-53.jpg" },
];
const POOLS = [
    ["Breath of the Dying", "Kyb's Worth", "Redline"],
    ["Hex", "Kaos", "Lyuda"],
    ["Bangarang", "Bitch", "Faisor"],
    ["Black Hole", "Krakatoa", "Trevonator"],
    ["AutoAimè", "Hellshock", "Night Hawkin"],
    ["Boom Sickle / Sickle", "Conference Call", "The Flood"],
    ["Flakker", "Laser-Sploder", "Mutant"],
    ["Light Show", "Nemesis", "Projectile Recursion"],
    ["Masterwork Crossbow", "Plus Ultra", "The Garcia"],
    ["Cutsman", "King's Call / Queen's Call", "Madcap"],
    ["Brainstormer", "Free Radical", "Ogre"],
    ["AAA", "Lucian's Call", "Nagata"],
    ["Carrier", "Hornet", "Infinity"],
    ["Face-puncher", "Moxxi's Bouncing Pair", "Sawbar"],
    ["Impaler", "Maggie", "Scourge"],
    ["Bone Shredder", "Crossroad", "Rowan's Call"],
    ["Predatory Lending", "Tankman's Shield", "The Butcher"],
    ["Ripper", "The Flood", "Tiggs' Boom"],
    ["Frozen Snowshoe", "Headsplosion", "Magnificent"],
    ["Bearcat", "D.N.A.", "Fastball"],
    ["Monocle", "Oldridian", "The Lob"],
    ["Hellfire", "Lead Sprinkler", "Messy Breakup"],
    ["Handsome Jackhammer", "King's Call / Queen's Call", "Sledge's Shotgun / Sledge's Super Shotgun"],
    ["ASMD", "Barrage", "Moonfire"],
    ["Damned", "Reflux", "Smart-Gun"],
    ["Ruby's Wrath", "T.K's Heatwave / T.K's Shockwave / T.K's Wave / The Tidal Wave", "The Horizon"],
    ["Mongol", "Surge", "Warlord"],
    ["Juliet's Dazzle", "Plaguebearer", "Woodblocker"],
    ["Firestorm (Sniper) / Storm", "Kaoson", "The Dictator"],
    ["Firestorm (Grenade)", "Hellwalker", "Shrike (Zane Skill Screen)"],
    ["Embrace the Pain / Pain is Power", "Red Queen", "Sand Hawk"],
    ["Brainstormer", "Hyperfocus XZ41", "The Duc"],
    ["Good Juju", "Nimble Jack", "Rebel Yell"],
    ["Hive", "One Pump Chump", "Whiskey Tango Foxtrot"],
    ["Cloud Kill", "Devastator", "EMP"],
    ["Destructo Spinner", "Re-Router", "Scorpio"],
    ["Mind-Killer", "Superball", "T.K's Heatwave / T.K's Shockwave / T.K's Wave / The Tidal Wave"],
    ["Gunerang", "Malak's Bane", "The Monarch"],
    ["Backburner", "Night Flyer", "Rectifier"],
    ["Scoville", "Ten Gallon", "Widowmaker"],
    ["Alchemist", "Clairvoyance", "Devils Foursum"],
    ["Blood-Starved Beast", "Tran-fusion", "Vanquisher"],
    ["Gatling Gun", "Light Show", "Long Musket"],
    ["Dark Army / Exceptional Dark Army / Exceptional Dark Army +", "Freeman", "Sellout"],
    ["Atlas Replay", "Phebert", "Psycho Stabber"],
    ["Quadomizer", "The Boring Gun", "The Transformer"],
    ["Roisen's Thorns", "Sleeping Giant", "Tunguska"],
    ["Linoge", "Star Helix", "Tsunami"],
    ["9-Volt", "Epicenter", "The Companion"],
    ["Embrace the Pain / Pain is Power", "Front Loader", "Jericho"],
    ["P.A.T. Mk. III", "Re-Charge Berner", "Try-Bolt"],
    ["Baby Maker", "Bekah", "Quasar"],
];
